apiVersion: v1
kind: Service
metadata:
  name: simple-request
  labels:
    app: simple-request
spec:
  type: NodePort
  #type: ClusterIP
  ports:
  - port: 30001
    targetPort: 30001
    nodePort: 30001
    protocol: TCP
    name: http
  selector:
    app: simple-request